# VPC
my-vpc-name = "my-vpc"
my-alb-sg-name= "my-alb-sg-name"
my-ec2-web-sg-name="my-ec2-web-sg-name"
my-rds-sg-name="my-rds-sg-name"
my-cidr-block = "10.0.0.0/16"
my-igw-name = "two-tier-igw"
my-public-cidr-block1="10.0.1.0/24"
my-web-public-subnet1="web-public-subnet-1"
my-public-cidr-block2="10.0.2.0/24"
my-web-public-subnet2="web-public-subnet-2"
my-pr-sub-rd1= "private-subnet-rds1"
my-pr-sub-rd2= "private-subnet-rds2"
my-nat_gw_eip-1 = "eip1"
my-nat_gw_eip-2= "eip2"
my-nat-1 = "nat-gw1"